mutation CriarAlterarEmpresa($data: EmpresaInput!) {
  criarAlterarEmpresa(data: $data) {
    id
    nome
    cnpj
    endereco
    telefone
    email
  }
}

query BuscarEmpresaPorId($buscarEmpresaPorIdId: Int!) {
  buscarEmpresaPorId(id: $buscarEmpresaPorIdId) {
    id
    nome
    cnpj
    endereco
    telefone
    email
  }
}

query FiltrarEmpresa($filter: EmpresaListInput!) {
  filtrarEmpresa(filter: $filter) {
    rows {
      id
      nome
      cnpj
      endereco
      telefone
      email
    }
    count
  }
}

query ListarEmpresa {
  listarEmpresa {
    id
    nome
    cnpj
    endereco
    telefone
    email
  }
}
