mutation CriarAlterarGrupoParticipante($data: GrupoParticipanteInput!) {
  criarAlterarGrupoParticipante(data: $data) {
    id
    descricao
    azure_group_id
    ativo
  }
}

query BuscarGrupoParticipantePorId($buscarGrupoParticipantePorIdId: Int!) {
  buscarGrupoParticipantePorId(id: $buscarGrupoParticipantePorIdId) {
    id
    descricao
    azure_group_id
    ativo
  }
}

query FiltrarGrupoParticipante($filter: GrupoParticipanteListInput!) {
  filtrarGrupoParticipante(filter: $filter) {
    rows {
      id
      descricao
      azure_group_id
      ativo
    }
    count
  }
}

query ListarGrupoParticipante {
  listarGrupoParticipante {
    id
    descricao
    azure_group_id
    ativo
  }
}

