query FiltrarParticipante($filter: ParticipanteListInput!) {
  filtrarParticipante(filter: $filter) {
    rows {
      id
      nome
      cpf
      cargo
      grupo
      dedo_cadastrado
      posicao_relatorio
      ativo
    }
    count
  }
}

query BuscarParticipantePorId($buscarParticipantePorIdId: Int!) {
  buscarParticipantePorId(id: $buscarParticipantePorIdId) {
    id
    nome
    cpf
    cargo
    data_cadastro
    grupo
    entidade
    digital
    foto
    ativo
    posicao_relatorio
    grupo_participante_id
    participante_id_azure
    dedo_cadastrado
    participante_foto_comparacao{
      id
      foto
    }
  }
}

mutation CriarAlterarParticipante($data: ParticipanteInput!) {
  criarAlterarParticipante(data: $data) {
    id
    nome
    cpf
    cargo
    data_cadastro
    grupo
    entidade
    digital
    foto
    dedo_cadastrado
    posicao_relatorio
    grupo_participante_id
    ativo
  }
}

query BuscarParticipanteViaDigital($digital: String!, $reunioes_ids: [Float!]!) {
  buscarParticipanteViaDigital(digital: $digital, reunioes_ids: $reunioes_ids) {
    id
    nome
    cpf
    cargo
    data_cadastro
    grupo
    entidade
    digital
    foto
    dedo_cadastrado
    ativo
  }
}


query buscarParticipantesFotosComparacao ($reunioes_ids: [Float!]!) {
  buscarParticipantesFotosComparacao(reunioes_ids: $reunioes_ids) {
    id
    nome
    cargo
    foto
    participante_foto_comparacao {
      id
      foto
    }
    reuniao_participante{
      id
      presente
    }
  }
}

mutation autenticarParticipanteFacial($participante_id: Int!, $reunioes_ids: [Float!]!) {
  autenticarParticipanteFacial(participante_id: $participante_id, reunioes_ids: $reunioes_ids) {
    id
    participante_id
    reuniao_id
    presente
    horario_presenca
  }
}

query BuscarQtdeReuniaoPorId($buscarQtdeReuniaoPorIdId: Int!) {
  buscarQtdeReuniaoPorId(id: $buscarQtdeReuniaoPorIdId) {
    qtde    
  }
}