query buscarReuniaoParticipantePorId($id: Int!) {
  buscarReuniaoParticipantePorId(id: $id) {
    id
    reuniao_id
    participante_id
    participante {
      nome
    }
    presente
    participante_grupo
    horario_presenca
  }
}

mutation criarAlterarReuniaoParticipante($data: ReuniaoParticipanteInput!) {
  criarAlterarReuniaoParticipante(data: $data) {
    id
    reuniao_id
    participante_id
    presente
    participante_grupo
    horario_presenca
  }
}