mutation CriarAlterarReuniao($data: ReuniaoInput!) {
  criarAlterarReuniao(data: $data) {
    id
    descricao
    data_reuniao
    grupo_participante_id
    horario
  }
}

query BuscarReuniaoPorId($buscarReuniaoPorIdId: Int!) {
  buscarReuniaoPorId(id: $buscarReuniaoPorIdId) {
    id
    descricao
    local
    grupo_participante_id
    data_reuniao
    horario
    reuniao_participante{
      id
      reuniao_id
      participante_id
      participante_grupo
      presente
      horario_presenca
      participante {
        nome
        grupo
        cargo
        posicao_relatorio
      }
    }
  }
}

query FiltrarReuniao($filter: ReuniaoListInput!) {
  filtrarReuniao(filter: $filter) {
    rows {
      id
      descricao
      data_reuniao
      horario
      grupo_participante_id
      grupo_participante {
        azure_group_id
      }
    }
    count
  }
}

mutation AzureFaceIdentify ($data: ReuniaoReconhecimentoInput!) {
  azureFaceIdentify(data: $data) {
    id
    nome
    cpf
    cargo
    participante_id_azure
    foto
    autenticado
  }
}